[project]
name = "hand-gesture-iot-sys"
version = "0.1.0"
description = "An IoT system that can be controlled with hand gestures."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "mediapipe==0.10.5",
    "opencv-python>=4.12.0.88",
]
